# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'UI.ui'
# Created by: PyQt5 UI code generator 5.10
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 680)
        Form.setMinimumSize(QtCore.QSize(800, 680))
        Form.setMaximumSize(QtCore.QSize(800, 680))
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 680))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 680))
        self.stackedWidget.setMaximumSize(QtCore.QSize(800, 680))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 280, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 360, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 440, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 360, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 280, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 440, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.page)
        self.pushButton_8.setGeometry(QtCore.QRect(450, 200, 150, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 60))
        self.pushButton_8.setMaximumSize(QtCore.QSize(150, 60))
        self.pushButton_8.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_33 = QtWidgets.QPushButton(self.page)
        self.pushButton_33.setGeometry(QtCore.QRect(210, 200, 150, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        self.pushButton_33.setStyleSheet("font: 14pt \"黑体\";\n"
"background-color: rgb(226, 226, 226);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(120, 50, 571, 91))
        self.label_7.setStyleSheet("font: 16pt \"华文隶书\";;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 20, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("font: 10pt \"Times New Roman\";\n"
"background-color: rgb(222, 222, 222);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_51 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_51.setGeometry(QtCore.QRect(610, 280, 81, 41))
        self.pushButton_51.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_51.setObjectName("pushButton_51")
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setGeometry(QtCore.QRect(190, 10, 401, 81))
        self.label_23.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.knn_testfile_path = QtWidgets.QLineEdit(self.page_5)
        self.knn_testfile_path.setGeometry(QtCore.QRect(110, 430, 491, 41))
        self.knn_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.knn_testfile_path.setObjectName("knn_testfile_path")
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setGeometry(QtCore.QRect(110, 90, 181, 71))
        self.label_28.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.knn_algo = QtWidgets.QComboBox(self.page_5)
        self.knn_algo.setGeometry(QtCore.QRect(550, 190, 91, 31))
        self.knn_algo.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.knn_algo.setObjectName("knn_algo")
        self.knn_algo.addItem("")
        self.knn_algo.addItem("")
        self.knn_algo.addItem("")
        self.knn_algo.addItem("")
        self.knn_test_res = QtWidgets.QLabel(self.page_5)
        self.knn_test_res.setGeometry(QtCore.QRect(150, 500, 491, 111))
        self.knn_test_res.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 75 11pt \"Times New Roman\";")
        self.knn_test_res.setAlignment(QtCore.Qt.AlignCenter)
        self.knn_test_res.setObjectName("knn_test_res")
        self.label_29 = QtWidgets.QLabel(self.page_5)
        self.label_29.setGeometry(QtCore.QRect(380, 190, 151, 31))
        self.label_29.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.svm_trainfile_btn_2 = QtWidgets.QPushButton(self.page_5)
        self.svm_trainfile_btn_2.setGeometry(QtCore.QRect(530, 280, 71, 41))
        self.svm_trainfile_btn_2.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.svm_trainfile_btn_2.setObjectName("svm_trainfile_btn_2")
        self.label_44 = QtWidgets.QLabel(self.page_5)
        self.label_44.setGeometry(QtCore.QRect(300, 370, 121, 31))
        self.label_44.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.knn_fea = QtWidgets.QSpinBox(self.page_5)
        self.knn_fea.setGeometry(QtCore.QRect(280, 110, 91, 31))
        self.knn_fea.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.knn_fea.setMinimum(1)
        self.knn_fea.setProperty("value", 3)
        self.knn_fea.setObjectName("knn_fea")
        self.knn_trainfile_path = QtWidgets.QLineEdit(self.page_5)
        self.knn_trainfile_path.setGeometry(QtCore.QRect(110, 280, 491, 41))
        self.knn_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.knn_trainfile_path.setObjectName("knn_trainfile_path")
        self.pushButton_50 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_50.setGeometry(QtCore.QRect(610, 430, 81, 41))
        self.pushButton_50.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_50.setObjectName("pushButton_50")
        self.knn_neig = QtWidgets.QSpinBox(self.page_5)
        self.knn_neig.setGeometry(QtCore.QRect(550, 110, 91, 31))
        self.knn_neig.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.knn_neig.setMinimum(2)
        self.knn_neig.setProperty("value", 5)
        self.knn_neig.setObjectName("knn_neig")
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setGeometry(QtCore.QRect(370, 100, 161, 51))
        self.label_24.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_39 = QtWidgets.QLabel(self.page_5)
        self.label_39.setGeometry(QtCore.QRect(110, 180, 171, 51))
        self.label_39.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.knn_train_res = QtWidgets.QLabel(self.page_5)
        self.knn_train_res.setGeometry(QtCore.QRect(410, 360, 101, 41))
        self.knn_train_res.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.knn_train_res.setText("")
        self.knn_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.knn_train_res.setObjectName("knn_train_res")
        self.knn_leafsize = QtWidgets.QSpinBox(self.page_5)
        self.knn_leafsize.setGeometry(QtCore.QRect(280, 190, 91, 31))
        self.knn_leafsize.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.knn_leafsize.setMinimum(2)
        self.knn_leafsize.setProperty("value", 30)
        self.knn_leafsize.setObjectName("knn_leafsize")
        self.pushButton_52 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_52.setGeometry(QtCore.QRect(530, 430, 71, 41))
        self.pushButton_52.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_52.setObjectName("pushButton_52")
        self.knn_train_time = QtWidgets.QLabel(self.page_5)
        self.knn_train_time.setGeometry(QtCore.QRect(170, 360, 101, 41))
        self.knn_train_time.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.knn_train_time.setText("")
        self.knn_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.knn_train_time.setObjectName("knn_train_time")
        self.label_68 = QtWidgets.QLabel(self.page_5)
        self.label_68.setGeometry(QtCore.QRect(100, 370, 81, 31))
        self.label_68.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.knn_train_sd = QtWidgets.QLabel(self.page_5)
        self.knn_train_sd.setGeometry(QtCore.QRect(590, 360, 101, 41))
        self.knn_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.knn_train_sd.setText("")
        self.knn_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.knn_train_sd.setObjectName("knn_train_sd")
        self.label_76 = QtWidgets.QLabel(self.page_5)
        self.label_76.setGeometry(QtCore.QRect(520, 370, 121, 31))
        self.label_76.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.knn_trainfile_path.raise_()
        self.pushButton_12.raise_()
        self.pushButton_51.raise_()
        self.label_23.raise_()
        self.knn_testfile_path.raise_()
        self.label_28.raise_()
        self.knn_algo.raise_()
        self.knn_test_res.raise_()
        self.label_29.raise_()
        self.svm_trainfile_btn_2.raise_()
        self.label_44.raise_()
        self.knn_fea.raise_()
        self.pushButton_50.raise_()
        self.knn_neig.raise_()
        self.label_24.raise_()
        self.label_39.raise_()
        self.knn_train_res.raise_()
        self.knn_leafsize.raise_()
        self.pushButton_52.raise_()
        self.knn_train_time.raise_()
        self.label_68.raise_()
        self.knn_train_sd.raise_()
        self.label_76.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.pushButton_13.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setGeometry(QtCore.QRect(380, 100, 61, 31))
        self.label_4.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_6)
        self.label_5.setGeometry(QtCore.QRect(500, 100, 61, 31))
        self.label_5.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.s_1 = QtWidgets.QSpinBox(self.page_6)
        self.s_1.setGeometry(QtCore.QRect(250, 200, 81, 31))
        self.s_1.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.s_1.setMinimum(1)
        self.s_1.setProperty("value", 3)
        self.s_1.setObjectName("s_1")
        self.k_1 = QtWidgets.QSpinBox(self.page_6)
        self.k_1.setGeometry(QtCore.QRect(250, 140, 81, 31))
        self.k_1.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.k_1.setMinimum(2)
        self.k_1.setMaximum(1000)
        self.k_1.setProperty("value", 32)
        self.k_1.setObjectName("k_1")
        self.s_3 = QtWidgets.QSpinBox(self.page_6)
        self.s_3.setGeometry(QtCore.QRect(500, 200, 71, 31))
        self.s_3.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.s_3.setMinimum(1)
        self.s_3.setProperty("value", 3)
        self.s_3.setObjectName("s_3")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        self.label_6.setGeometry(QtCore.QRect(620, 100, 71, 31))
        self.label_6.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.s_2 = QtWidgets.QSpinBox(self.page_6)
        self.s_2.setGeometry(QtCore.QRect(380, 200, 71, 31))
        self.s_2.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.s_2.setMinimum(1)
        self.s_2.setProperty("value", 3)
        self.s_2.setObjectName("s_2")
        self.label_3 = QtWidgets.QLabel(self.page_6)
        self.label_3.setGeometry(QtCore.QRect(250, 100, 71, 31))
        self.label_3.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.k_3 = QtWidgets.QSpinBox(self.page_6)
        self.k_3.setGeometry(QtCore.QRect(500, 140, 71, 31))
        self.k_3.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.k_3.setMinimum(2)
        self.k_3.setMaximum(1000)
        self.k_3.setProperty("value", 32)
        self.k_3.setObjectName("k_3")
        self.k_2 = QtWidgets.QSpinBox(self.page_6)
        self.k_2.setGeometry(QtCore.QRect(380, 140, 71, 31))
        self.k_2.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.k_2.setMinimum(2)
        self.k_2.setMaximum(1000)
        self.k_2.setProperty("value", 32)
        self.k_2.setObjectName("k_2")
        self.k_4 = QtWidgets.QSpinBox(self.page_6)
        self.k_4.setGeometry(QtCore.QRect(620, 140, 71, 31))
        self.k_4.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.k_4.setMinimum(2)
        self.k_4.setMaximum(1000)
        self.k_4.setProperty("value", 32)
        self.k_4.setObjectName("k_4")
        self.s_4 = QtWidgets.QSpinBox(self.page_6)
        self.s_4.setGeometry(QtCore.QRect(620, 200, 71, 31))
        self.s_4.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.s_4.setMinimum(1)
        self.s_4.setProperty("value", 3)
        self.s_4.setObjectName("s_4")
        self.label_13 = QtWidgets.QLabel(self.page_6)
        self.label_13.setGeometry(QtCore.QRect(140, 260, 81, 31))
        self.label_13.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_6)
        self.label_14.setGeometry(QtCore.QRect(340, 260, 161, 31))
        self.label_14.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.interation_num = QtWidgets.QSpinBox(self.page_6)
        self.interation_num.setGeometry(QtCore.QRect(500, 260, 91, 31))
        self.interation_num.setMinimum(10)
        self.interation_num.setMaximum(5000)
        self.interation_num.setObjectName("interation_num")
        self.lr = QtWidgets.QDoubleSpinBox(self.page_6)
        self.lr.setGeometry(QtCore.QRect(250, 260, 81, 31))
        self.lr.setDecimals(4)
        self.lr.setMaximum(1.0)
        self.lr.setSingleStep(0.0001)
        self.lr.setProperty("value", 0.0005)
        self.lr.setObjectName("lr")
        self.pushButton_35 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_35.setGeometry(QtCore.QRect(840, 350, 81, 41))
        self.pushButton_35.setObjectName("pushButton_35")
        self.label_18 = QtWidgets.QLabel(self.page_6)
        self.label_18.setGeometry(QtCore.QRect(100, 190, 151, 51))
        self.label_18.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(100, 140, 151, 41))
        self.label_19.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_19.setObjectName("label_19")
        self.cnn_res_show = QtWidgets.QLabel(self.page_6)
        self.cnn_res_show.setGeometry(QtCore.QRect(150, 510, 491, 111))
        self.cnn_res_show.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font:75 11pt \"Times New Roman\";")
        self.cnn_res_show.setAlignment(QtCore.Qt.AlignCenter)
        self.cnn_res_show.setObjectName("cnn_res_show")
        self.label_46 = QtWidgets.QLabel(self.page_6)
        self.label_46.setGeometry(QtCore.QRect(290, 400, 121, 31))
        self.label_46.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.cnn_test_btn = QtWidgets.QPushButton(self.page_6)
        self.cnn_test_btn.setGeometry(QtCore.QRect(600, 450, 81, 41))
        self.cnn_test_btn.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.cnn_test_btn.setObjectName("cnn_test_btn")
        self.cnn_train_browse_btn = QtWidgets.QPushButton(self.page_6)
        self.cnn_train_browse_btn.setGeometry(QtCore.QRect(520, 320, 71, 41))
        self.cnn_train_browse_btn.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.cnn_train_browse_btn.setObjectName("cnn_train_browse_btn")
        self.cnn_test_browse_btn = QtWidgets.QPushButton(self.page_6)
        self.cnn_test_browse_btn.setGeometry(QtCore.QRect(520, 450, 71, 41))
        self.cnn_test_browse_btn.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.cnn_test_browse_btn.setObjectName("cnn_test_browse_btn")
        self.cnn_train_btn = QtWidgets.QPushButton(self.page_6)
        self.cnn_train_btn.setGeometry(QtCore.QRect(600, 320, 81, 41))
        self.cnn_train_btn.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.cnn_train_btn.setObjectName("cnn_train_btn")
        self.cnn_test_file_path = QtWidgets.QLineEdit(self.page_6)
        self.cnn_test_file_path.setGeometry(QtCore.QRect(100, 450, 491, 41))
        self.cnn_test_file_path.setStyleSheet("font:75 12pt \"Times New Roman\";")
        self.cnn_test_file_path.setObjectName("cnn_test_file_path")
        self.cnn_train_res = QtWidgets.QLabel(self.page_6)
        self.cnn_train_res.setGeometry(QtCore.QRect(400, 390, 101, 41))
        self.cnn_train_res.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.cnn_train_res.setText("")
        self.cnn_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.cnn_train_res.setObjectName("cnn_train_res")
        self.cnn_train_file_path = QtWidgets.QLineEdit(self.page_6)
        self.cnn_train_file_path.setGeometry(QtCore.QRect(100, 320, 491, 41))
        self.cnn_train_file_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.cnn_train_file_path.setObjectName("cnn_train_file_path")
        self.label_65 = QtWidgets.QLabel(self.page_6)
        self.label_65.setGeometry(QtCore.QRect(190, 10, 411, 81))
        self.label_65.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.cnn_train_time = QtWidgets.QLabel(self.page_6)
        self.cnn_train_time.setGeometry(QtCore.QRect(160, 390, 101, 41))
        self.cnn_train_time.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.cnn_train_time.setText("")
        self.cnn_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.cnn_train_time.setObjectName("cnn_train_time")
        self.label_69 = QtWidgets.QLabel(self.page_6)
        self.label_69.setGeometry(QtCore.QRect(90, 400, 81, 31))
        self.label_69.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.label_77 = QtWidgets.QLabel(self.page_6)
        self.label_77.setGeometry(QtCore.QRect(510, 400, 121, 31))
        self.label_77.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.cnn_train_sd = QtWidgets.QLabel(self.page_6)
        self.cnn_train_sd.setGeometry(QtCore.QRect(580, 390, 101, 41))
        self.cnn_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.cnn_train_sd.setText("")
        self.cnn_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.cnn_train_sd.setObjectName("cnn_train_sd")
        self.cnn_train_file_path.raise_()
        self.cnn_test_file_path.raise_()
        self.pushButton_13.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.s_1.raise_()
        self.k_1.raise_()
        self.s_3.raise_()
        self.label_6.raise_()
        self.s_2.raise_()
        self.label_3.raise_()
        self.k_3.raise_()
        self.k_2.raise_()
        self.k_4.raise_()
        self.s_4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.interation_num.raise_()
        self.lr.raise_()
        self.pushButton_35.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.cnn_res_show.raise_()
        self.label_46.raise_()
        self.cnn_test_btn.raise_()
        self.cnn_train_browse_btn.raise_()
        self.cnn_test_browse_btn.raise_()
        self.cnn_train_btn.raise_()
        self.cnn_train_res.raise_()
        self.label_65.raise_()
        self.cnn_train_time.raise_()
        self.label_69.raise_()
        self.label_77.raise_()
        self.cnn_train_sd.raise_()
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.pushButton_14.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label = QtWidgets.QLabel(self.page_7)
        self.label.setGeometry(QtCore.QRect(160, 100, 181, 51))
        self.label.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_7)
        self.label_2.setGeometry(QtCore.QRect(440, 110, 111, 31))
        self.label_2.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_20 = QtWidgets.QLabel(self.page_7)
        self.label_20.setGeometry(QtCore.QRect(160, 190, 171, 41))
        self.label_20.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setGeometry(QtCore.QRect(440, 200, 91, 21))
        self.label_21.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.svm_decision = QtWidgets.QComboBox(self.page_7)
        self.svm_decision.setGeometry(QtCore.QRect(330, 190, 91, 31))
        self.svm_decision.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.svm_decision.setObjectName("svm_decision")
        self.svm_decision.addItem("")
        self.svm_decision.addItem("")
        self.svm_kernel = QtWidgets.QComboBox(self.page_7)
        self.svm_kernel.setGeometry(QtCore.QRect(560, 190, 91, 31))
        self.svm_kernel.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.svm_kernel.setObjectName("svm_kernel")
        self.svm_kernel.addItem("")
        self.svm_kernel.addItem("")
        self.svm_kernel.addItem("")
        self.svm_kernel.addItem("")
        self.svm_fea = QtWidgets.QSpinBox(self.page_7)
        self.svm_fea.setGeometry(QtCore.QRect(330, 110, 91, 31))
        self.svm_fea.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.svm_fea.setMinimum(1)
        self.svm_fea.setProperty("value", 3)
        self.svm_fea.setObjectName("svm_fea")
        self.svm_cefa = QtWidgets.QDoubleSpinBox(self.page_7)
        self.svm_cefa.setGeometry(QtCore.QRect(560, 110, 91, 31))
        self.svm_cefa.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.svm_cefa.setDecimals(2)
        self.svm_cefa.setMaximum(1.0)
        self.svm_cefa.setSingleStep(0.05)
        self.svm_cefa.setProperty("value", 0.6)
        self.svm_cefa.setObjectName("svm_cefa")
        self.svm_testfile_path = QtWidgets.QLineEdit(self.page_7)
        self.svm_testfile_path.setGeometry(QtCore.QRect(110, 430, 491, 41))
        self.svm_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.svm_testfile_path.setObjectName("svm_testfile_path")
        self.svm_test_res = QtWidgets.QLabel(self.page_7)
        self.svm_test_res.setGeometry(QtCore.QRect(150, 500, 491, 111))
        self.svm_test_res.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font:75 11pt \"Times New Roman\";")
        self.svm_test_res.setAlignment(QtCore.Qt.AlignCenter)
        self.svm_test_res.setObjectName("svm_test_res")
        self.label_43 = QtWidgets.QLabel(self.page_7)
        self.label_43.setGeometry(QtCore.QRect(300, 370, 121, 31))
        self.label_43.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.pushButton_49 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_49.setGeometry(QtCore.QRect(610, 430, 81, 41))
        self.pushButton_49.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_48 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_48.setGeometry(QtCore.QRect(530, 430, 71, 41))
        self.pushButton_48.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_40 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_40.setGeometry(QtCore.QRect(610, 280, 81, 41))
        self.pushButton_40.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_40.setObjectName("pushButton_40")
        self.svm_train_res = QtWidgets.QLabel(self.page_7)
        self.svm_train_res.setGeometry(QtCore.QRect(410, 360, 101, 41))
        self.svm_train_res.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(186, 183, 180);")
        self.svm_train_res.setText("")
        self.svm_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.svm_train_res.setObjectName("svm_train_res")
        self.svm_trainfile_path = QtWidgets.QLineEdit(self.page_7)
        self.svm_trainfile_path.setGeometry(QtCore.QRect(110, 280, 491, 41))
        self.svm_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.svm_trainfile_path.setObjectName("svm_trainfile_path")
        self.svm_trainfile_btn = QtWidgets.QPushButton(self.page_7)
        self.svm_trainfile_btn.setGeometry(QtCore.QRect(530, 280, 71, 41))
        self.svm_trainfile_btn.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.svm_trainfile_btn.setObjectName("svm_trainfile_btn")
        self.label_16 = QtWidgets.QLabel(self.page_7)
        self.label_16.setGeometry(QtCore.QRect(190, 10, 411, 81))
        self.label_16.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.svm_train_time = QtWidgets.QLabel(self.page_7)
        self.svm_train_time.setGeometry(QtCore.QRect(170, 360, 101, 41))
        self.svm_train_time.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(186, 183, 180);")
        self.svm_train_time.setText("")
        self.svm_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.svm_train_time.setObjectName("svm_train_time")
        self.label_70 = QtWidgets.QLabel(self.page_7)
        self.label_70.setGeometry(QtCore.QRect(100, 370, 81, 31))
        self.label_70.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.label_78 = QtWidgets.QLabel(self.page_7)
        self.label_78.setGeometry(QtCore.QRect(520, 370, 121, 31))
        self.label_78.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.svm_train_sd = QtWidgets.QLabel(self.page_7)
        self.svm_train_sd.setGeometry(QtCore.QRect(590, 360, 101, 41))
        self.svm_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.svm_train_sd.setText("")
        self.svm_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.svm_train_sd.setObjectName("svm_train_sd")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 20, 70, 30))
        self.pushButton_15.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.rf_features = QtWidgets.QSpinBox(self.page_8)
        self.rf_features.setGeometry(QtCore.QRect(430, 120, 91, 31))
        self.rf_features.setStyleSheet("font:75 12pt \"Times New Roman\";")
        self.rf_features.setMinimum(1)
        self.rf_features.setProperty("value", 3)
        self.rf_features.setObjectName("rf_features")
        self.label_25 = QtWidgets.QLabel(self.page_8)
        self.label_25.setGeometry(QtCore.QRect(260, 110, 181, 51))
        self.label_25.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_8)
        self.label_26.setGeometry(QtCore.QRect(260, 160, 181, 51))
        self.label_26.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_26.setObjectName("label_26")
        self.rf_fea_chose = QtWidgets.QComboBox(self.page_8)
        self.rf_fea_chose.setGeometry(QtCore.QRect(430, 170, 91, 31))
        self.rf_fea_chose.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.rf_fea_chose.setObjectName("rf_fea_chose")
        self.rf_fea_chose.addItem("")
        self.rf_fea_chose.addItem("")
        self.label_27 = QtWidgets.QLabel(self.page_8)
        self.label_27.setGeometry(QtCore.QRect(260, 210, 181, 51))
        self.label_27.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_27.setObjectName("label_27")
        self.rf_fea_split = QtWidgets.QComboBox(self.page_8)
        self.rf_fea_split.setGeometry(QtCore.QRect(430, 220, 91, 31))
        self.rf_fea_split.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.rf_fea_split.setObjectName("rf_fea_split")
        self.rf_fea_split.addItem("")
        self.rf_fea_split.addItem("")
        self.rf_train_acc = QtWidgets.QLabel(self.page_8)
        self.rf_train_acc.setGeometry(QtCore.QRect(400, 350, 101, 41))
        self.rf_train_acc.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(186, 183, 180);")
        self.rf_train_acc.setText("")
        self.rf_train_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.rf_train_acc.setObjectName("rf_train_acc")
        self.rf_trainfile_path = QtWidgets.QLineEdit(self.page_8)
        self.rf_trainfile_path.setGeometry(QtCore.QRect(100, 280, 491, 41))
        self.rf_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.rf_trainfile_path.setObjectName("rf_trainfile_path")
        self.pushButton_39 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_39.setGeometry(QtCore.QRect(600, 280, 81, 41))
        self.pushButton_39.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_39.setObjectName("pushButton_39")
        self.rf_res_show = QtWidgets.QLabel(self.page_8)
        self.rf_res_show.setGeometry(QtCore.QRect(150, 500, 491, 111))
        self.rf_res_show.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.rf_res_show.setAlignment(QtCore.Qt.AlignCenter)
        self.rf_res_show.setObjectName("rf_res_show")
        self.pushButton_41 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_41.setGeometry(QtCore.QRect(520, 420, 71, 41))
        self.pushButton_41.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_42.setGeometry(QtCore.QRect(520, 280, 71, 41))
        self.pushButton_42.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_42.setObjectName("pushButton_42")
        self.label_30 = QtWidgets.QLabel(self.page_8)
        self.label_30.setGeometry(QtCore.QRect(290, 360, 121, 31))
        self.label_30.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.rf_testfile_path = QtWidgets.QLineEdit(self.page_8)
        self.rf_testfile_path.setGeometry(QtCore.QRect(100, 420, 491, 41))
        self.rf_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.rf_testfile_path.setObjectName("rf_testfile_path")
        self.pushButton_47 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_47.setGeometry(QtCore.QRect(600, 420, 81, 41))
        self.pushButton_47.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_47.setObjectName("pushButton_47")
        self.label_17 = QtWidgets.QLabel(self.page_8)
        self.label_17.setGeometry(QtCore.QRect(190, 10, 401, 81))
        self.label_17.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_71 = QtWidgets.QLabel(self.page_8)
        self.label_71.setGeometry(QtCore.QRect(90, 360, 81, 31))
        self.label_71.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.rf_train_time = QtWidgets.QLabel(self.page_8)
        self.rf_train_time.setGeometry(QtCore.QRect(160, 350, 101, 41))
        self.rf_train_time.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(186, 183, 180);")
        self.rf_train_time.setText("")
        self.rf_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.rf_train_time.setObjectName("rf_train_time")
        self.label_79 = QtWidgets.QLabel(self.page_8)
        self.label_79.setGeometry(QtCore.QRect(510, 360, 121, 31))
        self.label_79.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.rf_train_sd = QtWidgets.QLabel(self.page_8)
        self.rf_train_sd.setGeometry(QtCore.QRect(580, 350, 101, 41))
        self.rf_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.rf_train_sd.setText("")
        self.rf_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.rf_train_sd.setObjectName("rf_train_sd")
        self.rf_testfile_path.raise_()
        self.pushButton_15.raise_()
        self.rf_features.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.rf_fea_chose.raise_()
        self.label_27.raise_()
        self.rf_fea_split.raise_()
        self.rf_train_acc.raise_()
        self.rf_trainfile_path.raise_()
        self.pushButton_39.raise_()
        self.rf_res_show.raise_()
        self.pushButton_41.raise_()
        self.pushButton_42.raise_()
        self.label_30.raise_()
        self.pushButton_47.raise_()
        self.label_17.raise_()
        self.label_71.raise_()
        self.rf_train_time.raise_()
        self.label_79.raise_()
        self.rf_train_sd.raise_()
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 20, 70, 30))
        self.pushButton_16.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_31 = QtWidgets.QLabel(self.page_9)
        self.label_31.setGeometry(QtCore.QRect(40, 120, 181, 21))
        self.label_31.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.page_9)
        self.label_32.setGeometry(QtCore.QRect(40, 180, 191, 21))
        self.label_32.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_9)
        self.label_33.setGeometry(QtCore.QRect(40, 240, 191, 21))
        self.label_33.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_9)
        self.label_34.setGeometry(QtCore.QRect(320, 120, 191, 21))
        self.label_34.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.page_9)
        self.label_35.setGeometry(QtCore.QRect(320, 180, 181, 31))
        self.label_35.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_9)
        self.label_36.setGeometry(QtCore.QRect(340, 240, 171, 21))
        self.label_36.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.page_9)
        self.label_37.setGeometry(QtCore.QRect(580, 120, 131, 21))
        self.label_37.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page_9)
        self.label_38.setGeometry(QtCore.QRect(580, 180, 141, 21))
        self.label_38.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.bpnn_num1 = QtWidgets.QSpinBox(self.page_9)
        self.bpnn_num1.setGeometry(QtCore.QRect(240, 120, 61, 21))
        self.bpnn_num1.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_num1.setMinimum(3)
        self.bpnn_num1.setMaximum(10000)
        self.bpnn_num1.setProperty("value", 32)
        self.bpnn_num1.setObjectName("bpnn_num1")
        self.bpnn_num2 = QtWidgets.QSpinBox(self.page_9)
        self.bpnn_num2.setGeometry(QtCore.QRect(240, 180, 61, 21))
        self.bpnn_num2.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_num2.setMinimum(3)
        self.bpnn_num2.setMaximum(10000)
        self.bpnn_num2.setProperty("value", 16)
        self.bpnn_num2.setObjectName("bpnn_num2")
        self.bpnn_num3 = QtWidgets.QSpinBox(self.page_9)
        self.bpnn_num3.setGeometry(QtCore.QRect(240, 240, 61, 21))
        self.bpnn_num3.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_num3.setMinimum(3)
        self.bpnn_num3.setMaximum(10000)
        self.bpnn_num3.setProperty("value", 16)
        self.bpnn_num3.setObjectName("bpnn_num3")
        self.bpnn_num4 = QtWidgets.QSpinBox(self.page_9)
        self.bpnn_num4.setGeometry(QtCore.QRect(510, 120, 61, 21))
        self.bpnn_num4.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_num4.setMinimum(3)
        self.bpnn_num4.setMaximum(10000)
        self.bpnn_num4.setProperty("value", 8)
        self.bpnn_num4.setObjectName("bpnn_num4")
        self.bpnn_interation = QtWidgets.QSpinBox(self.page_9)
        self.bpnn_interation.setGeometry(QtCore.QRect(700, 120, 61, 21))
        self.bpnn_interation.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_interation.setMinimum(10)
        self.bpnn_interation.setMaximum(10000)
        self.bpnn_interation.setProperty("value", 30)
        self.bpnn_interation.setObjectName("bpnn_interation")
        self.bpnn_fea_dim = QtWidgets.QSpinBox(self.page_9)
        self.bpnn_fea_dim.setGeometry(QtCore.QRect(700, 180, 61, 21))
        self.bpnn_fea_dim.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_fea_dim.setMinimum(1)
        self.bpnn_fea_dim.setMaximum(100)
        self.bpnn_fea_dim.setProperty("value", 3)
        self.bpnn_fea_dim.setObjectName("bpnn_fea_dim")
        self.bpnn_cr = QtWidgets.QDoubleSpinBox(self.page_9)
        self.bpnn_cr.setGeometry(QtCore.QRect(510, 180, 62, 22))
        self.bpnn_cr.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_cr.setDecimals(2)
        self.bpnn_cr.setMaximum(1.0)
        self.bpnn_cr.setSingleStep(0.002)
        self.bpnn_cr.setProperty("value", 0.25)
        self.bpnn_cr.setObjectName("bpnn_cr")
        self.bpnn_lr = QtWidgets.QDoubleSpinBox(self.page_9)
        self.bpnn_lr.setGeometry(QtCore.QRect(510, 240, 62, 22))
        self.bpnn_lr.setStyleSheet("font: 10pt \"Arial\";")
        self.bpnn_lr.setDecimals(4)
        self.bpnn_lr.setMinimum(0.0)
        self.bpnn_lr.setMaximum(1.0)
        self.bpnn_lr.setProperty("value", 0.0005)
        self.bpnn_lr.setObjectName("bpnn_lr")
        self.bpnn_train_res = QtWidgets.QLabel(self.page_9)
        self.bpnn_train_res.setGeometry(QtCore.QRect(400, 360, 101, 41))
        self.bpnn_train_res.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.bpnn_train_res.setText("")
        self.bpnn_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.bpnn_train_res.setObjectName("bpnn_train_res")
        self.pushButton_43 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_43.setGeometry(QtCore.QRect(520, 430, 71, 41))
        self.pushButton_43.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_43.setObjectName("pushButton_43")
        self.label_40 = QtWidgets.QLabel(self.page_9)
        self.label_40.setGeometry(QtCore.QRect(290, 370, 121, 31))
        self.label_40.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.pushButton_44 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_44.setGeometry(QtCore.QRect(520, 290, 71, 41))
        self.pushButton_44.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_45.setGeometry(QtCore.QRect(600, 290, 81, 41))
        self.pushButton_45.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_45.setObjectName("pushButton_45")
        self.bpnn_test_res = QtWidgets.QLabel(self.page_9)
        self.bpnn_test_res.setGeometry(QtCore.QRect(150, 500, 481, 111))
        self.bpnn_test_res.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: rgb(215, 215, 215);")
        self.bpnn_test_res.setAlignment(QtCore.Qt.AlignCenter)
        self.bpnn_test_res.setObjectName("bpnn_test_res")
        self.bpnn_trainfile_path = QtWidgets.QLineEdit(self.page_9)
        self.bpnn_trainfile_path.setGeometry(QtCore.QRect(100, 290, 491, 41))
        self.bpnn_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.bpnn_trainfile_path.setObjectName("bpnn_trainfile_path")
        self.bpnn_testfile_path = QtWidgets.QLineEdit(self.page_9)
        self.bpnn_testfile_path.setGeometry(QtCore.QRect(100, 430, 491, 41))
        self.bpnn_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.bpnn_testfile_path.setObjectName("bpnn_testfile_path")
        self.pushButton_46 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_46.setGeometry(QtCore.QRect(600, 430, 81, 41))
        self.pushButton_46.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_46.setObjectName("pushButton_46")
        self.label_22 = QtWidgets.QLabel(self.page_9)
        self.label_22.setGeometry(QtCore.QRect(190, 10, 411, 81))
        self.label_22.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.bpnn_train_time = QtWidgets.QLabel(self.page_9)
        self.bpnn_train_time.setGeometry(QtCore.QRect(160, 360, 101, 41))
        self.bpnn_train_time.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.bpnn_train_time.setText("")
        self.bpnn_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.bpnn_train_time.setObjectName("bpnn_train_time")
        self.label_72 = QtWidgets.QLabel(self.page_9)
        self.label_72.setGeometry(QtCore.QRect(90, 370, 81, 31))
        self.label_72.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.label_80 = QtWidgets.QLabel(self.page_9)
        self.label_80.setGeometry(QtCore.QRect(510, 370, 121, 31))
        self.label_80.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.bpnn_train_sd = QtWidgets.QLabel(self.page_9)
        self.bpnn_train_sd.setGeometry(QtCore.QRect(580, 360, 101, 41))
        self.bpnn_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.bpnn_train_sd.setText("")
        self.bpnn_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.bpnn_train_sd.setObjectName("bpnn_train_sd")
        self.bpnn_testfile_path.raise_()
        self.bpnn_trainfile_path.raise_()
        self.pushButton_16.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_38.raise_()
        self.bpnn_num1.raise_()
        self.bpnn_num2.raise_()
        self.bpnn_num3.raise_()
        self.bpnn_num4.raise_()
        self.bpnn_interation.raise_()
        self.bpnn_fea_dim.raise_()
        self.bpnn_cr.raise_()
        self.bpnn_lr.raise_()
        self.pushButton_43.raise_()
        self.label_40.raise_()
        self.pushButton_44.raise_()
        self.pushButton_45.raise_()
        self.bpnn_test_res.raise_()
        self.bpnn_train_res.raise_()
        self.pushButton_46.raise_()
        self.label_22.raise_()
        self.bpnn_train_time.raise_()
        self.label_72.raise_()
        self.label_80.raise_()
        self.bpnn_train_sd.raise_()
        self.stackedWidget.addWidget(self.page_9)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_17 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 20, 70, 30))
        self.pushButton_17.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_41 = QtWidgets.QLabel(self.page_2)
        self.label_41.setGeometry(QtCore.QRect(190, 10, 401, 81))
        self.label_41.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.page_2)
        self.label_42.setGeometry(QtCore.QRect(120, 100, 181, 51))
        self.label_42.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_45 = QtWidgets.QLabel(self.page_2)
        self.label_45.setGeometry(QtCore.QRect(120, 200, 181, 51))
        self.label_45.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.pso_fea = QtWidgets.QSpinBox(self.page_2)
        self.pso_fea.setGeometry(QtCore.QRect(290, 110, 91, 31))
        self.pso_fea.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pso_fea.setMinimum(1)
        self.pso_fea.setProperty("value", 3)
        self.pso_fea.setObjectName("pso_fea")
        self.label_47 = QtWidgets.QLabel(self.page_2)
        self.label_47.setGeometry(QtCore.QRect(120, 150, 181, 51))
        self.label_47.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.pso_interation = QtWidgets.QSpinBox(self.page_2)
        self.pso_interation.setGeometry(QtCore.QRect(290, 160, 91, 31))
        self.pso_interation.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pso_interation.setMinimum(2)
        self.pso_interation.setMaximum(1000)
        self.pso_interation.setProperty("value", 30)
        self.pso_interation.setObjectName("pso_interation")
        self.pso_num = QtWidgets.QSpinBox(self.page_2)
        self.pso_num.setGeometry(QtCore.QRect(290, 210, 91, 31))
        self.pso_num.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pso_num.setMinimum(2)
        self.pso_num.setMaximum(1000)
        self.pso_num.setProperty("value", 3)
        self.pso_num.setObjectName("pso_num")
        self.label_48 = QtWidgets.QLabel(self.page_2)
        self.label_48.setGeometry(QtCore.QRect(400, 150, 181, 51))
        self.label_48.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.page_2)
        self.label_49.setGeometry(QtCore.QRect(400, 100, 181, 51))
        self.label_49.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.pso_lr1 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.pso_lr1.setGeometry(QtCore.QRect(580, 110, 91, 31))
        self.pso_lr1.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pso_lr1.setMaximum(10.0)
        self.pso_lr1.setProperty("value", 0.8)
        self.pso_lr1.setObjectName("pso_lr1")
        self.pso_lr2 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.pso_lr2.setGeometry(QtCore.QRect(580, 160, 91, 31))
        self.pso_lr2.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pso_lr2.setMaximum(10.0)
        self.pso_lr2.setProperty("value", 0.8)
        self.pso_lr2.setObjectName("pso_lr2")
        self.pso_test_res = QtWidgets.QLabel(self.page_2)
        self.pso_test_res.setGeometry(QtCore.QRect(150, 500, 481, 111))
        self.pso_test_res.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: rgb(215, 215, 215);")
        self.pso_test_res.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_test_res.setObjectName("pso_test_res")
        self.pso_trainfile_path = QtWidgets.QLineEdit(self.page_2)
        self.pso_trainfile_path.setGeometry(QtCore.QRect(100, 290, 491, 41))
        self.pso_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.pso_trainfile_path.setObjectName("pso_trainfile_path")
        self.pso_testfile_path = QtWidgets.QLineEdit(self.page_2)
        self.pso_testfile_path.setGeometry(QtCore.QRect(100, 430, 491, 41))
        self.pso_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.pso_testfile_path.setObjectName("pso_testfile_path")
        self.label_50 = QtWidgets.QLabel(self.page_2)
        self.label_50.setGeometry(QtCore.QRect(290, 370, 121, 31))
        self.label_50.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.pso_train_res = QtWidgets.QLabel(self.page_2)
        self.pso_train_res.setGeometry(QtCore.QRect(400, 360, 101, 41))
        self.pso_train_res.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.pso_train_res.setText("")
        self.pso_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_train_res.setObjectName("pso_train_res")
        self.pushButton_53 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_53.setGeometry(QtCore.QRect(520, 430, 71, 41))
        self.pushButton_53.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_54.setGeometry(QtCore.QRect(600, 430, 81, 41))
        self.pushButton_54.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_55.setGeometry(QtCore.QRect(520, 290, 71, 41))
        self.pushButton_55.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_56.setGeometry(QtCore.QRect(600, 290, 81, 41))
        self.pushButton_56.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_56.setObjectName("pushButton_56")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(390, 210, 181, 31))
        self.label_8.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pso_bpnn_interation = QtWidgets.QSpinBox(self.page_2)
        self.pso_bpnn_interation.setGeometry(QtCore.QRect(580, 210, 91, 31))
        self.pso_bpnn_interation.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.pso_bpnn_interation.setMinimum(2)
        self.pso_bpnn_interation.setMaximum(1000)
        self.pso_bpnn_interation.setProperty("value", 30)
        self.pso_bpnn_interation.setObjectName("pso_bpnn_interation")
        self.pso_train_time = QtWidgets.QLabel(self.page_2)
        self.pso_train_time.setGeometry(QtCore.QRect(160, 360, 101, 41))
        self.pso_train_time.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.pso_train_time.setText("")
        self.pso_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_train_time.setObjectName("pso_train_time")
        self.label_73 = QtWidgets.QLabel(self.page_2)
        self.label_73.setGeometry(QtCore.QRect(90, 370, 81, 31))
        self.label_73.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.label_81 = QtWidgets.QLabel(self.page_2)
        self.label_81.setGeometry(QtCore.QRect(510, 370, 121, 31))
        self.label_81.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.pso_train_sd = QtWidgets.QLabel(self.page_2)
        self.pso_train_sd.setGeometry(QtCore.QRect(580, 360, 101, 41))
        self.pso_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.pso_train_sd.setText("")
        self.pso_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.pso_train_sd.setObjectName("pso_train_sd")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 20, 70, 30))
        self.pushButton_10.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gwo_test_res = QtWidgets.QLabel(self.page_3)
        self.gwo_test_res.setGeometry(QtCore.QRect(160, 500, 481, 111))
        self.gwo_test_res.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: rgb(215, 215, 215);")
        self.gwo_test_res.setAlignment(QtCore.Qt.AlignCenter)
        self.gwo_test_res.setObjectName("gwo_test_res")
        self.label_51 = QtWidgets.QLabel(self.page_3)
        self.label_51.setGeometry(QtCore.QRect(290, 370, 121, 31))
        self.label_51.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gwo_num = QtWidgets.QSpinBox(self.page_3)
        self.gwo_num.setGeometry(QtCore.QRect(260, 210, 91, 31))
        self.gwo_num.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.gwo_num.setMinimum(2)
        self.gwo_num.setMaximum(1000)
        self.gwo_num.setProperty("value", 3)
        self.gwo_num.setObjectName("gwo_num")
        self.label_52 = QtWidgets.QLabel(self.page_3)
        self.label_52.setGeometry(QtCore.QRect(90, 200, 181, 51))
        self.label_52.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gwo_testfile_path = QtWidgets.QLineEdit(self.page_3)
        self.gwo_testfile_path.setGeometry(QtCore.QRect(100, 430, 491, 41))
        self.gwo_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.gwo_testfile_path.setObjectName("gwo_testfile_path")
        self.gwo_interation = QtWidgets.QSpinBox(self.page_3)
        self.gwo_interation.setGeometry(QtCore.QRect(260, 160, 91, 31))
        self.gwo_interation.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.gwo_interation.setMinimum(2)
        self.gwo_interation.setMaximum(1000)
        self.gwo_interation.setProperty("value", 30)
        self.gwo_interation.setObjectName("gwo_interation")
        self.gwo_trainfile_path = QtWidgets.QLineEdit(self.page_3)
        self.gwo_trainfile_path.setGeometry(QtCore.QRect(100, 290, 491, 41))
        self.gwo_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.gwo_trainfile_path.setObjectName("gwo_trainfile_path")
        self.pushButton_57 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_57.setGeometry(QtCore.QRect(600, 430, 81, 41))
        self.pushButton_57.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_57.setObjectName("pushButton_57")
        self.label_53 = QtWidgets.QLabel(self.page_3)
        self.label_53.setGeometry(QtCore.QRect(90, 100, 181, 51))
        self.label_53.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.pushButton_58 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_58.setGeometry(QtCore.QRect(520, 290, 71, 41))
        self.pushButton_58.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_59.setGeometry(QtCore.QRect(520, 430, 71, 41))
        self.pushButton_59.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_59.setObjectName("pushButton_59")
        self.label_54 = QtWidgets.QLabel(self.page_3)
        self.label_54.setGeometry(QtCore.QRect(190, 10, 401, 81))
        self.label_54.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.pushButton_60 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_60.setGeometry(QtCore.QRect(600, 290, 81, 41))
        self.pushButton_60.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_60.setObjectName("pushButton_60")
        self.label_55 = QtWidgets.QLabel(self.page_3)
        self.label_55.setGeometry(QtCore.QRect(390, 150, 181, 51))
        self.label_55.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_3)
        self.label_56.setGeometry(QtCore.QRect(90, 150, 181, 51))
        self.label_56.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gwo_train_res = QtWidgets.QLabel(self.page_3)
        self.gwo_train_res.setGeometry(QtCore.QRect(400, 360, 101, 41))
        self.gwo_train_res.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.gwo_train_res.setText("")
        self.gwo_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.gwo_train_res.setObjectName("gwo_train_res")
        self.label_57 = QtWidgets.QLabel(self.page_3)
        self.label_57.setGeometry(QtCore.QRect(390, 100, 181, 51))
        self.label_57.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gwo_fea = QtWidgets.QSpinBox(self.page_3)
        self.gwo_fea.setGeometry(QtCore.QRect(260, 110, 91, 31))
        self.gwo_fea.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.gwo_fea.setMinimum(1)
        self.gwo_fea.setProperty("value", 3)
        self.gwo_fea.setObjectName("gwo_fea")
        self.gwo_down = QtWidgets.QSpinBox(self.page_3)
        self.gwo_down.setGeometry(QtCore.QRect(550, 110, 91, 31))
        self.gwo_down.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.gwo_down.setMinimum(2)
        self.gwo_down.setMaximum(1000)
        self.gwo_down.setProperty("value", 3)
        self.gwo_down.setObjectName("gwo_down")
        self.gwo_up = QtWidgets.QSpinBox(self.page_3)
        self.gwo_up.setGeometry(QtCore.QRect(550, 160, 91, 31))
        self.gwo_up.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.gwo_up.setMinimum(2)
        self.gwo_up.setMaximum(1000)
        self.gwo_up.setProperty("value", 150)
        self.gwo_up.setObjectName("gwo_up")
        self.label_66 = QtWidgets.QLabel(self.page_3)
        self.label_66.setGeometry(QtCore.QRect(370, 200, 191, 51))
        self.label_66.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.gwo_interation_2 = QtWidgets.QSpinBox(self.page_3)
        self.gwo_interation_2.setGeometry(QtCore.QRect(550, 210, 91, 31))
        self.gwo_interation_2.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.gwo_interation_2.setMinimum(2)
        self.gwo_interation_2.setMaximum(1000)
        self.gwo_interation_2.setProperty("value", 30)
        self.gwo_interation_2.setObjectName("gwo_interation_2")
        self.gwo_train_time = QtWidgets.QLabel(self.page_3)
        self.gwo_train_time.setGeometry(QtCore.QRect(160, 360, 101, 41))
        self.gwo_train_time.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.gwo_train_time.setText("")
        self.gwo_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.gwo_train_time.setObjectName("gwo_train_time")
        self.label_74 = QtWidgets.QLabel(self.page_3)
        self.label_74.setGeometry(QtCore.QRect(90, 370, 81, 31))
        self.label_74.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.label_82 = QtWidgets.QLabel(self.page_3)
        self.label_82.setGeometry(QtCore.QRect(510, 370, 121, 31))
        self.label_82.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.gwo_train_sd = QtWidgets.QLabel(self.page_3)
        self.gwo_train_sd.setGeometry(QtCore.QRect(580, 360, 101, 41))
        self.gwo_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.gwo_train_sd.setText("")
        self.gwo_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.gwo_train_sd.setObjectName("gwo_train_sd")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 20, 70, 30))
        self.pushButton_11.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.ssa_low = QtWidgets.QSpinBox(self.page_4)
        self.ssa_low.setGeometry(QtCore.QRect(570, 110, 91, 31))
        self.ssa_low.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.ssa_low.setMinimum(2)
        self.ssa_low.setMaximum(1000)
        self.ssa_low.setProperty("value", 3)
        self.ssa_low.setObjectName("ssa_low")
        self.ssa_testfile_path = QtWidgets.QLineEdit(self.page_4)
        self.ssa_testfile_path.setGeometry(QtCore.QRect(100, 430, 491, 41))
        self.ssa_testfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.ssa_testfile_path.setObjectName("ssa_testfile_path")
        self.label_58 = QtWidgets.QLabel(self.page_4)
        self.label_58.setGeometry(QtCore.QRect(100, 100, 181, 51))
        self.label_58.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.page_4)
        self.label_59.setGeometry(QtCore.QRect(100, 150, 181, 51))
        self.label_59.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.page_4)
        self.label_60.setGeometry(QtCore.QRect(290, 370, 121, 31))
        self.label_60.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.pushButton_61 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_61.setGeometry(QtCore.QRect(600, 430, 81, 41))
        self.pushButton_61.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_61.setObjectName("pushButton_61")
        self.ssa_test_res = QtWidgets.QLabel(self.page_4)
        self.ssa_test_res.setGeometry(QtCore.QRect(160, 500, 481, 111))
        self.ssa_test_res.setStyleSheet("font: 11pt \"Times New Roman\";\n"
"background-color: rgb(215, 215, 215);")
        self.ssa_test_res.setAlignment(QtCore.Qt.AlignCenter)
        self.ssa_test_res.setObjectName("ssa_test_res")
        self.label_61 = QtWidgets.QLabel(self.page_4)
        self.label_61.setGeometry(QtCore.QRect(410, 100, 181, 51))
        self.label_61.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.pushButton_62 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_62.setGeometry(QtCore.QRect(520, 430, 71, 41))
        self.pushButton_62.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_62.setObjectName("pushButton_62")
        self.label_62 = QtWidgets.QLabel(self.page_4)
        self.label_62.setGeometry(QtCore.QRect(410, 150, 181, 51))
        self.label_62.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.ssa_up = QtWidgets.QSpinBox(self.page_4)
        self.ssa_up.setGeometry(QtCore.QRect(570, 160, 91, 31))
        self.ssa_up.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.ssa_up.setMinimum(2)
        self.ssa_up.setMaximum(1000)
        self.ssa_up.setProperty("value", 150)
        self.ssa_up.setObjectName("ssa_up")
        self.pushButton_63 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_63.setGeometry(QtCore.QRect(520, 290, 71, 41))
        self.pushButton_63.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_63.setObjectName("pushButton_63")
        self.ssa_trainfile_path = QtWidgets.QLineEdit(self.page_4)
        self.ssa_trainfile_path.setGeometry(QtCore.QRect(100, 290, 491, 41))
        self.ssa_trainfile_path.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.ssa_trainfile_path.setObjectName("ssa_trainfile_path")
        self.ssa_fea = QtWidgets.QSpinBox(self.page_4)
        self.ssa_fea.setGeometry(QtCore.QRect(270, 110, 91, 31))
        self.ssa_fea.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.ssa_fea.setMinimum(1)
        self.ssa_fea.setProperty("value", 3)
        self.ssa_fea.setObjectName("ssa_fea")
        self.label_63 = QtWidgets.QLabel(self.page_4)
        self.label_63.setGeometry(QtCore.QRect(100, 200, 181, 51))
        self.label_63.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.ssa_interation = QtWidgets.QSpinBox(self.page_4)
        self.ssa_interation.setGeometry(QtCore.QRect(270, 160, 91, 31))
        self.ssa_interation.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.ssa_interation.setMinimum(2)
        self.ssa_interation.setMaximum(1000)
        self.ssa_interation.setProperty("value", 30)
        self.ssa_interation.setObjectName("ssa_interation")
        self.label_64 = QtWidgets.QLabel(self.page_4)
        self.label_64.setGeometry(QtCore.QRect(190, 10, 401, 81))
        self.label_64.setStyleSheet("font: 12pt \"Times New Roman\";\n"
"background-color: rgb(248, 248, 186);")
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.ssa_train_res = QtWidgets.QLabel(self.page_4)
        self.ssa_train_res.setGeometry(QtCore.QRect(400, 360, 101, 41))
        self.ssa_train_res.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.ssa_train_res.setText("")
        self.ssa_train_res.setAlignment(QtCore.Qt.AlignCenter)
        self.ssa_train_res.setObjectName("ssa_train_res")
        self.ssa_num = QtWidgets.QSpinBox(self.page_4)
        self.ssa_num.setGeometry(QtCore.QRect(270, 210, 91, 31))
        self.ssa_num.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.ssa_num.setMinimum(2)
        self.ssa_num.setMaximum(1000)
        self.ssa_num.setProperty("value", 3)
        self.ssa_num.setObjectName("ssa_num")
        self.pushButton_64 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_64.setGeometry(QtCore.QRect(600, 290, 81, 41))
        self.pushButton_64.setStyleSheet("background-color: rgb(222, 222, 222);\n"
"font: 11pt \"Times New Roman\";")
        self.pushButton_64.setObjectName("pushButton_64")
        self.ssa_bpnn_interation = QtWidgets.QSpinBox(self.page_4)
        self.ssa_bpnn_interation.setGeometry(QtCore.QRect(570, 210, 91, 31))
        self.ssa_bpnn_interation.setStyleSheet("font: 11pt \"Times New Roman\";")
        self.ssa_bpnn_interation.setMinimum(2)
        self.ssa_bpnn_interation.setMaximum(1000)
        self.ssa_bpnn_interation.setProperty("value", 30)
        self.ssa_bpnn_interation.setObjectName("ssa_bpnn_interation")
        self.label_67 = QtWidgets.QLabel(self.page_4)
        self.label_67.setGeometry(QtCore.QRect(380, 200, 201, 51))
        self.label_67.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.ssa_train_time = QtWidgets.QLabel(self.page_4)
        self.ssa_train_time.setGeometry(QtCore.QRect(160, 360, 101, 41))
        self.ssa_train_time.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"background-color: rgb(193, 193, 193);")
        self.ssa_train_time.setText("")
        self.ssa_train_time.setAlignment(QtCore.Qt.AlignCenter)
        self.ssa_train_time.setObjectName("ssa_train_time")
        self.label_75 = QtWidgets.QLabel(self.page_4)
        self.label_75.setGeometry(QtCore.QRect(90, 370, 81, 31))
        self.label_75.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.label_83 = QtWidgets.QLabel(self.page_4)
        self.label_83.setGeometry(QtCore.QRect(510, 370, 121, 31))
        self.label_83.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.ssa_train_sd = QtWidgets.QLabel(self.page_4)
        self.ssa_train_sd.setGeometry(QtCore.QRect(580, 360, 101, 41))
        self.ssa_train_sd.setStyleSheet("background-color: rgb(186, 183, 180);\n"
"font: 12pt \"Times New Roman\";")
        self.ssa_train_sd.setText("")
        self.ssa_train_sd.setAlignment(QtCore.Qt.AlignCenter)
        self.ssa_train_sd.setObjectName("ssa_train_sd")
        self.ssa_trainfile_path.raise_()
        self.pushButton_11.raise_()
        self.ssa_low.raise_()
        self.ssa_testfile_path.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_60.raise_()
        self.pushButton_61.raise_()
        self.ssa_test_res.raise_()
        self.label_61.raise_()
        self.pushButton_62.raise_()
        self.label_62.raise_()
        self.ssa_up.raise_()
        self.pushButton_63.raise_()
        self.ssa_fea.raise_()
        self.label_63.raise_()
        self.ssa_interation.raise_()
        self.label_64.raise_()
        self.ssa_train_res.raise_()
        self.ssa_num.raise_()
        self.pushButton_64.raise_()
        self.ssa_bpnn_interation.raise_()
        self.label_67.raise_()
        self.ssa_train_time.raise_()
        self.label_75.raise_()
        self.label_83.raise_()
        self.ssa_train_sd.raise_()
        self.stackedWidget.addWidget(self.page_4)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_14.clicked.connect(Form.exit_main)
        self.pushButton_16.clicked.connect(Form.exit_main)
        self.pushButton_7.clicked.connect(Form.ssa_bpnn_show)
        self.pushButton_2.clicked.connect(Form.svm_show)
        self.pushButton_5.clicked.connect(Form.pso_bpnn_show)
        self.pushButton_51.clicked.connect(Form.knn_train)
        self.svm_trainfile_btn_2.clicked.connect(Form.knn_trainfile_chose)
        self.pushButton_8.clicked.connect(Form.cnn_show)
        self.pushButton_3.clicked.connect(Form.bpnn_show)
        self.pushButton_15.clicked.connect(Form.exit_main)
        self.pushButton_53.clicked.connect(Form.pso_testfile_chose)
        self.pushButton_54.clicked.connect(Form.pso_test)
        self.pushButton_12.clicked.connect(Form.exit_main)
        self.pushButton_55.clicked.connect(Form.pso_trainfile_chose)
        self.pushButton_6.clicked.connect(Form.rf_show)
        self.pushButton_10.clicked.connect(Form.exit_main)
        self.pushButton_13.clicked.connect(Form.exit_main)
        self.pushButton_41.clicked.connect(Form.rf_testfile_show)
        self.svm_trainfile_btn.clicked.connect(Form.svm_trainfile_lab)
        self.pushButton_46.clicked.connect(Form.bpnn_test)
        self.pushButton_44.clicked.connect(Form.bpnn_trainfile_chose)
        self.cnn_test_btn.clicked.connect(Form.cnn_test)
        self.pushButton_47.clicked.connect(Form.rf_test)
        self.pushButton_33.clicked.connect(Form.knn_show)
        self.pushButton_42.clicked.connect(Form.rf_trainfile_show)
        self.cnn_test_browse_btn.clicked.connect(Form.cnn_testfile_chose_show)
        self.pushButton_50.clicked.connect(Form.knn_test)
        self.pushButton_43.clicked.connect(Form.bpnn_testfile_chose)
        self.pushButton_56.clicked.connect(Form.pso_train)
        self.pushButton_39.clicked.connect(Form.rf_train)
        self.pushButton_4.clicked.connect(Form.gwo_bpnn_show)
        self.pushButton_40.clicked.connect(Form.svm_train)
        self.pushButton_45.clicked.connect(Form.bpnn_train)
        self.pushButton_49.clicked.connect(Form.svm_test)
        self.pushButton_11.clicked.connect(Form.exit_main)
        self.cnn_train_browse_btn.clicked.connect(Form.cnn_trainfile_chose_show)
        self.cnn_train_btn.clicked.connect(Form.cnn_train)
        self.pushButton_48.clicked.connect(Form.svm_testfile_lab)
        self.pushButton_52.clicked.connect(Form.knn_testfile_chose)
        self.pushButton_17.clicked.connect(Form.exit_main)
        self.pushButton_59.clicked.connect(Form.gwo_testfile_chose)
        self.pushButton_63.clicked.connect(Form.ssa_trainfile_chose)
        self.pushButton_57.clicked.connect(Form.gwo_test)
        self.pushButton_58.clicked.connect(Form.gwo_trainfile_chose)
        self.pushButton_61.clicked.connect(Form.ssa_test)
        self.pushButton_60.clicked.connect(Form.gwo_train)
        self.pushButton_62.clicked.connect(Form.ssa_testfile_chose)
        self.pushButton_64.clicked.connect(Form.ssa_train)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "SVM"))
        self.pushButton_3.setText(_translate("Form", "BPNN"))
        self.pushButton_4.setText(_translate("Form", "GWO-BPNN"))
        self.pushButton_5.setText(_translate("Form", "PSO-BPNN"))
        self.pushButton_6.setText(_translate("Form", "RF"))
        self.pushButton_7.setText(_translate("Form", "SSA-BPNN"))
        self.pushButton_8.setText(_translate("Form", "CNN"))
        self.pushButton_33.setText(_translate("Form", "KNN"))
        self.label_7.setText(_translate("Form", "Multi-algorithm Pattern Recognition Platform"))
        self.pushButton_12.setText(_translate("Form", "Back"))
        self.pushButton_51.setText(_translate("Form", "Train"))
        self.label_23.setText(_translate("Form", "KNN Pattern Recognition"))
        self.knn_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.label_28.setText(_translate("Form", "Fea_dims:"))
        self.knn_algo.setItemText(0, _translate("Form", "auto"))
        self.knn_algo.setItemText(1, _translate("Form", "ball_tree"))
        self.knn_algo.setItemText(2, _translate("Form", "kd_tree"))
        self.knn_algo.setItemText(3, _translate("Form", "brute"))
        self.knn_test_res.setText(_translate("Form", "Detection result display area"))
        self.label_29.setText(_translate("Form", "Algorithm:"))
        self.svm_trainfile_btn_2.setText(_translate("Form", "Open"))
        self.label_44.setText(_translate("Form", "Accuracy："))
        self.knn_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.pushButton_50.setText(_translate("Form", "Test"))
        self.label_24.setText(_translate("Form", "N_neighbors:"))
        self.label_39.setText(_translate("Form", "Leaf_size:"))
        self.pushButton_52.setText(_translate("Form", "Open"))
        self.label_68.setText(_translate("Form", "Time："))
        self.label_76.setText(_translate("Form", "sd："))
        self.pushButton_13.setText(_translate("Form", "Back"))
        self.label_4.setText(_translate("Form", "No.2"))
        self.label_5.setText(_translate("Form", "No.3"))
        self.label_6.setText(_translate("Form", "No.4"))
        self.label_3.setText(_translate("Form", "No.1"))
        self.label_13.setText(_translate("Form", "lr:"))
        self.label_14.setText(_translate("Form", "Interation_num:"))
        self.interation_num.setStyleSheet(_translate("Form", "font: 12pt \"Times New Roman\";"))
        self.lr.setStyleSheet(_translate("Form", "font: 12pt \"Times New Roman\";"))
        self.pushButton_35.setText(_translate("Form", "浏览"))
        self.label_18.setText(_translate("Form", "Kernel_length:"))
        self.label_19.setText(_translate("Form", "Kernel_num:"))
        self.cnn_res_show.setText(_translate("Form", "Detection result display area"))
        self.label_46.setText(_translate("Form", "Accuracy:"))
        self.cnn_test_btn.setText(_translate("Form", "Test"))
        self.cnn_train_browse_btn.setText(_translate("Form", "Open"))
        self.cnn_test_browse_btn.setText(_translate("Form", "Open"))
        self.cnn_train_btn.setText(_translate("Form", "Train"))
        self.cnn_test_file_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.cnn_train_file_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.label_65.setText(_translate("Form", "CNN Pattern Recognition"))
        self.label_69.setText(_translate("Form", "Time:"))
        self.label_77.setText(_translate("Form", "sd："))
        self.pushButton_14.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "Fea_dims:"))
        self.label_2.setText(_translate("Form", "C:"))
        self.label_20.setText(_translate("Form", "Decision_func:"))
        self.label_21.setText(_translate("Form", "Kernel:"))
        self.svm_decision.setItemText(0, _translate("Form", "ovr"))
        self.svm_decision.setItemText(1, _translate("Form", "ovo"))
        self.svm_kernel.setItemText(0, _translate("Form", "rbf"))
        self.svm_kernel.setItemText(1, _translate("Form", "linear"))
        self.svm_kernel.setItemText(2, _translate("Form", "poly"))
        self.svm_kernel.setItemText(3, _translate("Form", "sigmod"))
        self.svm_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.svm_test_res.setText(_translate("Form", "Detection result display area"))
        self.label_43.setText(_translate("Form", "Accuracy:"))
        self.pushButton_49.setText(_translate("Form", "Test"))
        self.pushButton_48.setText(_translate("Form", "Open"))
        self.pushButton_40.setText(_translate("Form", "Train"))
        self.svm_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.svm_trainfile_btn.setText(_translate("Form", "Open"))
        self.label_16.setText(_translate("Form", "SVM Pattern Recognition"))
        self.label_70.setText(_translate("Form", "Time:"))
        self.label_78.setText(_translate("Form", "sd："))
        self.pushButton_15.setText(_translate("Form", "Back"))
        self.label_25.setText(_translate("Form", "Fea-dims:"))
        self.label_26.setText(_translate("Form", "Criterion"))
        self.rf_fea_chose.setItemText(0, _translate("Form", "gini"))
        self.rf_fea_chose.setItemText(1, _translate("Form", "entropy"))
        self.label_27.setText(_translate("Form", "Fea-split:"))
        self.rf_fea_split.setItemText(0, _translate("Form", "best"))
        self.rf_fea_split.setItemText(1, _translate("Form", "random"))
        self.rf_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.pushButton_39.setText(_translate("Form", "Train"))
        self.rf_res_show.setText(_translate("Form", "Detection result display area"))
        self.pushButton_41.setText(_translate("Form", "Open"))
        self.pushButton_42.setText(_translate("Form", "Open"))
        self.label_30.setText(_translate("Form", "Accuracy："))
        self.rf_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.pushButton_47.setText(_translate("Form", "Test"))
        self.label_17.setText(_translate("Form", "RF Pattern Recognition"))
        self.label_71.setText(_translate("Form", "Time："))
        self.label_79.setText(_translate("Form", "sd："))
        self.pushButton_16.setText(_translate("Form", "Back"))
        self.label_31.setText(_translate("Form", "First-layer-neur:"))
        self.label_32.setText(_translate("Form", "Second-layer-neur:"))
        self.label_33.setText(_translate("Form", "Third-layer-neur:"))
        self.label_34.setText(_translate("Form", "Fourth_layer_neur:"))
        self.label_35.setText(_translate("Form", "Cross-validation："))
        self.label_36.setText(_translate("Form", "Lr："))
        self.label_37.setText(_translate("Form", "Interation："))
        self.label_38.setText(_translate("Form", "Fea-dims："))
        self.pushButton_43.setText(_translate("Form", "Open"))
        self.label_40.setText(_translate("Form", "Accuracy："))
        self.pushButton_44.setText(_translate("Form", "Open"))
        self.pushButton_45.setText(_translate("Form", "Train"))
        self.bpnn_test_res.setText(_translate("Form", "Detection result display area"))
        self.bpnn_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.bpnn_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.pushButton_46.setText(_translate("Form", "Test"))
        self.label_22.setText(_translate("Form", "BPNN Pattern Recognition"))
        self.label_72.setText(_translate("Form", "Time："))
        self.label_80.setText(_translate("Form", "sd："))
        self.pushButton_17.setText(_translate("Form", "Back"))
        self.label_41.setText(_translate("Form", "PSO-BPNN Pattern Recognition"))
        self.label_42.setText(_translate("Form", "Fea_dims:"))
        self.label_45.setText(_translate("Form", "Particle-Num:"))
        self.label_47.setText(_translate("Form", "PSO_interation："))
        self.label_48.setText(_translate("Form", "C2："))
        self.label_49.setText(_translate("Form", "C1："))
        self.pso_test_res.setText(_translate("Form", "Detection result display area"))
        self.pso_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.pso_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.label_50.setText(_translate("Form", "Accuracy："))
        self.pushButton_53.setText(_translate("Form", "Open"))
        self.pushButton_54.setText(_translate("Form", "Test"))
        self.pushButton_55.setText(_translate("Form", "Open"))
        self.pushButton_56.setText(_translate("Form", "Train"))
        self.label_8.setText(_translate("Form", "BPNN-interation:"))
        self.label_73.setText(_translate("Form", "Time："))
        self.label_81.setText(_translate("Form", "sd："))
        self.pushButton_10.setText(_translate("Form", "Back"))
        self.gwo_test_res.setText(_translate("Form", "Detection result display area"))
        self.label_51.setText(_translate("Form", "Accuracy："))
        self.label_52.setText(_translate("Form", "Wolves-Num:"))
        self.gwo_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.gwo_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.pushButton_57.setText(_translate("Form", "Test"))
        self.label_53.setText(_translate("Form", "Fea-dims:"))
        self.pushButton_58.setText(_translate("Form", "Open"))
        self.pushButton_59.setText(_translate("Form", "Open"))
        self.label_54.setText(_translate("Form", "GWO-BPNN Pattern Recognition"))
        self.pushButton_60.setText(_translate("Form", "Train"))
        self.label_55.setText(_translate("Form", "Up："))
        self.label_56.setText(_translate("Form", "GWO-interation："))
        self.label_57.setText(_translate("Form", "Low："))
        self.label_66.setText(_translate("Form", "BPNN-interation："))
        self.label_74.setText(_translate("Form", "Time："))
        self.label_82.setText(_translate("Form", "sd："))
        self.pushButton_11.setText(_translate("Form", "Back"))
        self.ssa_testfile_path.setPlaceholderText(_translate("Form", "Please select the testing sample data"))
        self.label_58.setText(_translate("Form", "Fea-dims:"))
        self.label_59.setText(_translate("Form", "SSA-interation："))
        self.label_60.setText(_translate("Form", "Accuracy:"))
        self.pushButton_61.setText(_translate("Form", "Test"))
        self.ssa_test_res.setText(_translate("Form", "Detection result display area"))
        self.label_61.setText(_translate("Form", "Low："))
        self.pushButton_62.setText(_translate("Form", "Open"))
        self.label_62.setText(_translate("Form", "Up："))
        self.pushButton_63.setText(_translate("Form", "Open"))
        self.ssa_trainfile_path.setPlaceholderText(_translate("Form", "Please select the training sample data"))
        self.label_63.setText(_translate("Form", "Sparrow-Num:"))
        self.label_64.setText(_translate("Form", "SSA-BPNN Partten Recogniton"))
        self.pushButton_64.setText(_translate("Form", "Train"))
        self.label_67.setText(_translate("Form", "BPNN-interation："))
        self.label_75.setText(_translate("Form", "Time:"))
        self.label_83.setText(_translate("Form", "sd："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

